# -*- coding: UTF-8 -*-
Bank.create!(:code => '001', :name => 'Banco do Brasil')
Bank.create!(:code => '003', :name => 'Banco da Amazônia')
Bank.create!(:code => '004', :name => 'Banco do Nordeste')
Bank.create!(:code => '021', :name => 'Banestes')
Bank.create!(:code => '025', :name => 'Banco Alfa')
Bank.create!(:code => '027', :name => 'Besc')
Bank.create!(:code => '029', :name => 'Banerj')
Bank.create!(:code => '031', :name => 'Banco Beg')
Bank.create!(:code => '033', :name => 'Banco Santander Banespa')
Bank.create!(:code => '036', :name => 'Banco Bem')
Bank.create!(:code => '037', :name => 'Banpará')
Bank.create!(:code => '038', :name => 'Banestado')
Bank.create!(:code => '039', :name => 'BEP')
Bank.create!(:code => '040', :name => 'Banco Cargill')
Bank.create!(:code => '041', :name => 'Banrisul')
Bank.create!(:code => '044', :name => 'BVA')
Bank.create!(:code => '045', :name => 'Banco Opportunity')
Bank.create!(:code => '047', :name => 'Banese')
Bank.create!(:code => '062', :name => 'Hipercard')
Bank.create!(:code => '063', :name => 'Ibibank')
Bank.create!(:code => '065', :name => 'Lemon Bank')
Bank.create!(:code => '066', :name => 'Banco Morgan Stanley Dean Witter')
Bank.create!(:code => '069', :name => 'BPN Brasil')
Bank.create!(:code => '070', :name => 'Banco de Brasília – BRB')
Bank.create!(:code => '072', :name => 'Banco Rural')
Bank.create!(:code => '073', :name => 'Banco Popular')
Bank.create!(:code => '074', :name => 'Banco J. Safra')
Bank.create!(:code => '075', :name => 'Banco CR2')
Bank.create!(:code => '076', :name => 'Banco KDB')
Bank.create!(:code => '096', :name => 'Banco BMF')
Bank.create!(:code => '104', :name => 'Caixa Econômica Federal')
Bank.create!(:code => '107', :name => 'Banco BBM')
Bank.create!(:code => '116', :name => 'Banco Único')
Bank.create!(:code => '151', :name => 'Nossa Caixa')
Bank.create!(:code => '175', :name => 'Banco Finasa')
Bank.create!(:code => '184', :name => 'Banco Itaú BBA')
Bank.create!(:code => '204', :name => 'American Express Bank')
Bank.create!(:code => '208', :name => 'Banco Pactual')
Bank.create!(:code => '212', :name => 'Banco Matone')
Bank.create!(:code => '213', :name => 'Banco Arbi')
Bank.create!(:code => '214', :name => 'Banco Dibens')
Bank.create!(:code => '217', :name => 'Banco Joh Deere')
Bank.create!(:code => '218', :name => 'Banco Bonsucesso')
Bank.create!(:code => '222', :name => 'Banco Calyon Brasil')
Bank.create!(:code => '224', :name => 'Banco Fibra')
Bank.create!(:code => '225', :name => 'Banco Brascan')
Bank.create!(:code => '229', :name => 'Banco Cruzeiro')
Bank.create!(:code => '230', :name => 'Unicard')
Bank.create!(:code => '233', :name => 'Banco GE Capital')
Bank.create!(:code => '237', :name => 'Bradesco')
Bank.create!(:code => '241', :name => 'Banco Clássico')
Bank.create!(:code => '243', :name => 'Banco Stock Máxima')
Bank.create!(:code => '246', :name => 'Banco ABC Brasil')
Bank.create!(:code => '248', :name => 'Banco Boavista Interatlântico')
Bank.create!(:code => '249', :name => 'Investcred Unibanco')
Bank.create!(:code => '250', :name => 'Banco Schahin')
Bank.create!(:code => '252', :name => 'Fininvest')
Bank.create!(:code => '254', :name => 'Paraná Banco')
Bank.create!(:code => '263', :name => 'Banco Cacique')
Bank.create!(:code => '265', :name => 'Banco Fator')
Bank.create!(:code => '266', :name => 'Banco Cédula')
Bank.create!(:code => '300', :name => 'Banco de la Nación Argentina')
Bank.create!(:code => '318', :name => 'Banco BMG')
Bank.create!(:code => '320', :name => 'Banco Industrial e Comercial
')
Bank.create!(:code => '356', :name => 'ABN Amro Real ')
Bank.create!(:code => '341', :name => 'Itau')
Bank.create!(:code => '347', :name => 'Sudameris')
Bank.create!(:code => '351', :name => 'Banco Santander')
Bank.create!(:code => '353', :name => 'Banco Santander Brasil')
Bank.create!(:code => '366', :name => 'Banco Societe Generale Brasil')
Bank.create!(:code => '370', :name => 'Banco WestLB')
Bank.create!(:code => '376', :name => 'JP Morgan')
Bank.create!(:code => '389', :name => 'Banco Mercantil do Brasil')
Bank.create!(:code => '394', :name => 'Banco Mercantil de Crédito')
Bank.create!(:code => '399', :name => 'HSBC')
Bank.create!(:code => '409', :name => 'Unibanco')
Bank.create!(:code => '412', :name => 'Banco Capital')
Bank.create!(:code => '422', :name => 'Banco Safra')
Bank.create!(:code => '453', :name => 'Banco Rural')
Bank.create!(:code => '456', :name => 'Banco Tokyo Mitsubishi UFJ')
Bank.create!(:code => '464', :name => 'Banco Sumitomo Mitsui Brasileiro')
Bank.create!(:code => '477', :name => 'Citibank')
Bank.create!(:code => '479', :name => 'Itaubank (antigo Bank Boston)')
Bank.create!(:code => '487', :name => 'Deutsche Bank')
Bank.create!(:code => '488', :name => 'Banco Morgan Guaranty')
Bank.create!(:code => '492', :name => 'Banco NMB Postbank')
Bank.create!(:code => '494', :name => 'Banco la República Oriental del Uruguay')
Bank.create!(:code => '495', :name => 'Banco La Provincia de Buenos Aires')
Bank.create!(:code => '505', :name => 'Banco Credit Suisse')
Bank.create!(:code => '600', :name => 'Banco Luso Brasileiro')
Bank.create!(:code => '604', :name => 'Banco Industrial')
Bank.create!(:code => '610', :name => 'Banco VR')
Bank.create!(:code => '611', :name => 'Banco Paulista')
Bank.create!(:code => '612', :name => 'Banco Guanabara')
Bank.create!(:code => '613', :name => 'Banco Pecunia')
Bank.create!(:code => '623', :name => 'Banco Panamericano')
Bank.create!(:code => '626', :name => 'Banco Ficsa')
Bank.create!(:code => '630', :name => 'Banco Intercap')
Bank.create!(:code => '633', :name => 'Banco Rendimento')
Bank.create!(:code => '634', :name => 'Banco Triângulo')
Bank.create!(:code => '637', :name => 'Banco Sofisa')
Bank.create!(:code => '638', :name => 'Banco Prosper')
Bank.create!(:code => '643', :name => 'Banco Pine')
Bank.create!(:code => '652', :name => 'Itaú Holding Financeira')
Bank.create!(:code => '653', :name => 'Banco Indusval')
Bank.create!(:code => '654', :name => 'Banco A.J. Renner')
Bank.create!(:code => '655', :name => 'Banco Votorantim')
Bank.create!(:code => '707', :name => 'Banco Daycoval')
Bank.create!(:code => '719', :name => 'Banif')
Bank.create!(:code => '721', :name => 'Banco Credibel')
Bank.create!(:code => '734', :name => 'Banco Gerdau')
Bank.create!(:code => '735', :name => 'Banco Pottencial')
Bank.create!(:code => '738', :name => 'Banco Morada')
Bank.create!(:code => '739', :name => 'Banco Galvão de Negócios')
Bank.create!(:code => '740', :name => 'Banco Barclays')
Bank.create!(:code => '741', :name => 'BRP')
Bank.create!(:code => '743', :name => 'Banco Semear')
Bank.create!(:code => '745', :name => 'Banco Citibank')
Bank.create!(:code => '746', :name => 'Banco Modal')
Bank.create!(:code => '747', :name => 'Banco Rabobank International')
Bank.create!(:code => '748', :name => 'Banco Cooperativo Sicredi')
Bank.create!(:code => '749', :name => 'Banco Simples')
Bank.create!(:code => '751', :name => 'Dresdner Bank')
Bank.create!(:code => '752', :name => 'BNP Paribas')
Bank.create!(:code => '753', :name => 'Banco Comercial Uruguai')
Bank.create!(:code => '755', :name => 'Banco Merrill Lynch')
Bank.create!(:code => '756', :name => 'Banco Cooperativo do Brasil')
Bank.create!(:code => '757', :name => 'KEB')